Update main yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Builb Test and push
+name: Build Test and push
 on: [push]
 env:
   IMAGE_NAME: student_service
@@ -15,20 +15,41 @@ jobs:
         docker build . -t $REPO_NAME/$IMAGE_NAME
     - name: run docker
       run: |
-        docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
+        docker run -d -p 8080:8080 $REPO_NAME/$IMAGE_NAME:latest && \
           docker ps && sleep 5
+
+    - name: "Check files existence"
+      uses: andstor/file-existence-action@v2
+      with:
+        files: "postman/collection.json,postman/environment.json"
+        fail: true
+
     - name: Run API Tests
       id: run-newman
-      uses: anthonyvscode/newman-action@v1
+      uses: anthonyvscode/newman-action@master
       with:
         collection: postman/collection.json
         environment: postman/environment.json
         reporters: cli
-        iterationCount: 3
+        bail: true
 
-    - name: Output summary to console
-      run: echo ${{ steps.run-newman.outputs.summary }}
+    - name: Check if we failed
+      id: fail-check
+      shell: bash
+      env:
+        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
+      run: |
+        printf '%s\n' "$JSON_DOC" > summary.json
+        cat summary.json
+        if grep -q Collection summary.json; then
+          echo "failed=false" >> $GITHUB_OUTPUT;
+        else
+          echo "failed=true" >> $GITHUB_OUTPUT;
+        fi
 
+    - name: fail if empty
+      if: ${{ steps.fail-check.outputs.failed == 'true' }}
+      run: exit 1
 
     - name: Login to Container Registry
       uses: docker/login-action@v1
